### ISSUE TITLE
Prevent installation of tests component

### ISSUE THREAD

**Issue by littlewu2508** [RadeonOpenCompute/rocm-cmake#158]
https://github.com/RadeonOpenCompute/ROCm/issues/1905 discussed that currently rocm packages install test binaries as tests component. https://github.com/RadeonOpenCompute/ROCm/issues/1905#issuecomment-1449165578 pointed out that it may be used in cpack, but for distos which does not use cpack, the default installation includes test binaries (if they are built).

Is it possible that `rocm-install` function add an `EXCLUDE_FROM_ALL` option when `COMPONENTS` matches `tests`? This requires minimum cmake version of 3.6 (https://cmake.org/cmake/help/latest/command/install.html)

**Comment by cgmb** [comment]
We were just talking about this last week and I think that was the solution that we considering. Though, it would be nice to have a configuration option like `-DROCM_INSTALL_TESTS_EXCLUDE_FROM_ALL=OFF` so users can explicitly choose the current behaviour.

The situation on Debian has changed somewhat since I made the comment you linked. The tests are now being packaged so that users can run them on their own systems (and so that the CI can install the tests without having to rebuild them).

**Comment by pfultz2** [comment]
Rocm cmake already uses `EXCLUDE_FROM_ALL` to install the tests:

https://github.com/ROCm/rocm-cmake/blob/e76fefc2e9f7839a52c2499770ef359ad4b4adcf/share/rocmcmakebuildtools/cmake/ROCMTest.cmake#L224

There is also an `install-tests` target that can be used to install tests if you want to install them:

https://github.com/ROCm/rocm-cmake/blob/e76fefc2e9f7839a52c2499770ef359ad4b4adcf/share/rocmcmakebuildtools/cmake/ROCMTest.cmake#L22
